//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARarchitectures
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDB()
        {
            this.PhotoDB = new HashSet<PhotoDB>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public Nullable<int> CurrentPhotoId { get; set; }
        public Nullable<int> IdCountryManufacturer { get; set; }
        public Nullable<int> IdBodyType { get; set; }
        public int Mass { get; set; }
        public double EngineCapacity { get; set; }
        public int Power { get; set; }
        public int YearOfIssue { get; set; }
    
        public virtual BodyTypeDB BodyTypeDB { get; set; }
        public virtual CountryManufacturerDB CountryManufacturerDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoDB> PhotoDB { get; set; }
    }
}
