$(document).ready(function(){
	$('.slider-it').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    responsive:{
	        0:{
	            items:1
	        },
	        600:{
	            items:1
	        },
	        1000:{
	            items:1
	        }
	    }
	});
	$('.slider-it-partners').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    responsive:{
	        0:{
	            items:6
	        },
	        600:{
	            items:6
	        },
	        1000:{
	            items:6
	        }
	    }
	});
	
	$(".owl-next").html("");
	$(".owl-prev").html("");
})
