//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsArchitecureEntities : DbContext
    {
        public CarsArchitecureEntities()
            : base("name=CarsArchitecureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyTypeDB> BodyTypeDB { get; set; }
        public virtual DbSet<CarDB> CarDB { get; set; }
        public virtual DbSet<CountryManufacturerDB> CountryManufacturerDB { get; set; }
        public virtual DbSet<PhotoDB> PhotoDB { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
