//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLanquage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceLanquage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exam.ResourceLanquage", typeof(ResourceLanquage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhotoBtn {
            get {
                return ResourceManager.GetString("AddPhotoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body type.
        /// </summary>
        public static string BodyTypeLb {
            get {
                return ResourceManager.GetString("BodyTypeLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next photo.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous photo.
        /// </summary>
        public static string btnPrev {
            get {
                return ResourceManager.GetString("btnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose auto.
        /// </summary>
        public static string ChooseAuto {
            get {
                return ResourceManager.GetString("ChooseAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country manufacturer.
        /// </summary>
        public static string CountryManufacturerLb {
            get {
                return ResourceManager.GetString("CountryManufacturerLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkMn {
            get {
                return ResourceManager.GetString("DarkMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine capacity.
        /// </summary>
        public static string EngineCapacityLb {
            get {
                return ResourceManager.GetString("EngineCapacityLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language in the application, change the keyboard layout to the language you need (English or Russian) and run the application again..
        /// </summary>
        public static string HelpLge {
            get {
                return ResourceManager.GetString("HelpLge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        public static string HelpMn {
            get {
                return ResourceManager.GetString("HelpMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanquages.
        /// </summary>
        public static string LanquagesMn {
            get {
                return ResourceManager.GetString("LanquagesMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightMn {
            get {
                return ResourceManager.GetString("LightMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List automobile.
        /// </summary>
        public static string ListAuto {
            get {
                return ResourceManager.GetString("ListAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string MassLb {
            get {
                return ResourceManager.GetString("MassLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelLb {
            get {
                return ResourceManager.GetString("ModelLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLb {
            get {
                return ResourceManager.GetString("NameLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo this car.
        /// </summary>
        public static string PhotoCar {
            get {
                return ResourceManager.GetString("PhotoCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string PowerLb {
            get {
                return ResourceManager.GetString("PowerLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveBtn {
            get {
                return ResourceManager.GetString("RemoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body type.
        /// </summary>
        public static string SortBodyType {
            get {
                return ResourceManager.GetString("SortBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country manufacturer.
        /// </summary>
        public static string SortCountryManufacturer {
            get {
                return ResourceManager.GetString("SortCountryManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine capacity.
        /// </summary>
        public static string SortEngineCapacity {
            get {
                return ResourceManager.GetString("SortEngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string SortMass {
            get {
                return ResourceManager.GetString("SortMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string SortModel {
            get {
                return ResourceManager.GetString("SortModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string SortPower {
            get {
                return ResourceManager.GetString("SortPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of issue.
        /// </summary>
        public static string SortYearOfIssue {
            get {
                return ResourceManager.GetString("SortYearOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemesMn {
            get {
                return ResourceManager.GetString("ThemesMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah of issue.
        /// </summary>
        public static string YeahOfIssueLb {
            get {
                return ResourceManager.GetString("YeahOfIssueLb", resourceCulture);
            }
        }
    }
}
